### ISSUE TITLE
implement unit tests

### ISSUE THREAD

**Issue by sarlam** [Terag/kadok#11]
# What

implement tests for existing features

# Why

The base code is small enough to have a good coverage now and keep it along the project

# Who will benefit

Developers confidence

# Technical criteria

to see with @Terag and @elBichon

**Comment by Terag** [comment]
Regarding the unit tests, it could be a good solution rely on Golang tools as the standard library already include testing features that can be used for unit testing.

For more: https://golang.org/pkg/testing/
