### ISSUE TITLE
Automatically deploy in dev

### ISSUE THREAD

**Issue by sarlam** [Terag/kadok#17]
# What

Once a PR is approved and merged, the bot should be deploy automatically through github actions to a development environment

# Why

Reduce the time between a line of code being written and being available for tests

# Who will benefit

DevOps

# Technical criteria

  - [ ] #16 must be done

to be refined

**Comment by Terag** [comment]
This issue is not required anymore as we decided to not run a dev environment and only have a master branch for production. I close it for now.
