### ISSUE TITLE
Define and implements RBAC

### ISSUE THREAD

**Issue by sarlam** [Terag/kadok#3]
# What

bot commands should be conditioned by user roles and rights

# Why

To allow implementation of commands to manage and moderate the bot or for the bot to access safely sensible information from third parties (minecraft)

# Who will benefits

Bot operators, final users

# Functional criteria

  * A list of roles should be available for PO, Developers and Admin of discord servers with access description
  * A command should always have a role associated to it
  * Per default a user should have a role Anonymous
  * When invoking a command with not enough rights it should display a message to the user

**Comment by Terag** [comment]
Closed by pull request  #9
