### ISSUE TITLE
answering via a short youtube video given a text input

### ISSUE THREAD

**Issue by elBichon** [Terag/kadok#33]
### **What**

A command to display answer request with an ad hoc youtube video saying the text instead of writing text.

**Why**
To make interactions with the bot funnier

**Who will benefit**
Users

**functional criteria**

- It should not include Kaamelott characters
- It should display a video whose text is close to a real answer
- If there is no actual good answer, a default answer that could work in any situation should be used

**Comment by Terag** [comment]
Does it mean that the bot searches for the right video using youtube's API or the bot already has a list of possible youtube videos to choose from ?

**Comment by elBichon** [comment]
The bot would have a list of videos, just like the text based answers but with the corresponding link to a video

**Comment by Terag** [comment]
It is close to what we wanted to do with the bot but with audio files. I personally like the idea!

It would then make sense to create a media package that will include audio and video formats.

**Comment by elBichon** [comment]
the video would be played as a youtube embedded video, not as showing the video file itself

**Comment by Terag** [comment]
Understood, however the bot will still have a library of URL for these video.

Also it is important to note that a discord bot can only share the video link in the chat.
We should check if the bot can stream videos, from the documentation it seems that it is not yet supported for bots.
