### ISSUE TITLE
Make the bot multi tenant (multi server)

### ISSUE THREAD

**Issue by sarlam** [Terag/kadok#37]
# What

Make the bot able to handle multiple servers at the same time

# Why

to open it to more people/server

# Functionnal ciretria

- Should be able to add the same instance to multiple servers

**Comment by spiderweak** [comment]
# How

Ressource from discord documentation regarding guilds (aka 'servers')
https://discord.com/developers/docs/resources/guild
https://pkg.go.dev/github.com/bwmarrin/discordgo#Guild
https://bwmarrin.github.io/discordgo <- dead link
