### ISSUE TITLE
Display a help message on `kadok help`

### ISSUE THREAD

**Issue by sarlam** [Terag/kadok#4]
# What

when invoking `kadok help` the user should be displayed a list of available commands

# Why

to help the user navigate through the available commands

# Who will benefits

Users

# functional criteria

  * It should not include Kaamelott characters
  * It should list all the command per categories

**Comment by elBichon** [comment]
"It should include moderation commands on a separate section" what does this criteria means ?

**Comment by sarlam** [comment]
Indeed, I was anticipating some specific functions that doesn't exist yet, I'll remove that criteria
